### PR TITLE
reader not closed on error + null-check on published value

### PR DESCRIPTION
**Pull request by rpjengaard**
A fix for issue #14 (https://github.com/umco/umbraco-unversion/issues/14)

### CODE REVIEW

**Comment by netaddicts** [comment]
@leekelleher @mattbrailsford Any idea when this can be merged so we could have a new version instead of working with a forked 'unsupported' version? Our db is growing dramatically due to this issue at the moment
Of course we could execute the sql statement ourselves, but rather not to this way due to different configurations for different doc types

**Comment by mattbrailsford** [comment]
Sorry, my bad. Looks good to me.

**Comment by NikRimington** [comment]
Hey wonderful Umco peeps. Did this get released in the end (I can see it was merged) as I'm getting the same error thrown on a 7.13.2 site with the latest nuget installed.

**Comment by netaddicts** [comment]
@NikRimington i don't think so, but you can still grab the (alpha)nuget package from here https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.UnVersion, we use it in production site with no issues

**Pull request merged**
